##version: "3.9"
services:
  backend:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./scraper/normalized:/app/scraper/normalized
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    ports:
      - "4321:4321"
    depends_on:
      - backend