services:
  - type: web
    name: BrandMatch
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildContext: .
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
envVars:
  - key: PUBLIC_API_URL
    value: https://brandmatch.onrender.com
