services:
  - type: web
    name: BrandMatch
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildContext: .
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
