services:
  - type: web
    name: ganado-frontend
    env: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    buildContext: ./frontend
    buildCommand: npm install && npm run build
    envVars: []
    autoDeploy: true

  - type: web
    name: ganado-backend
    env: docker
    plan: free
    dockerfilePath: ./api/Dockerfile
    buildContext: ./api
    envVars: []
    autoDeploy: true