services:
  - type: web
    name: ganado-frontend
    env: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    buildCommand: npm install && npm run build
    startCommand: serve -s dist -l 4321
    envVars: []
    autoDeploy: true
    disk:
      name: chroma-db
      mountPath: /app/chroma_db
      sizeGB: 1

  - type: web
    name: ganado-backend
    env: docker
    plan: free
    dockerfilePath: ./api/Dockerfile
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars: []
    autoDeploy: true
    disk:
      name: chroma-db
      mountPath: /app/chroma_db
      sizeGB: 1